import sys
sys.path.append("..")
from _paths import *

iids = (
    expand("rnd_{s}s_sim_{t}t_abcde", s=(200, 400), t=(50, 100, 150, 200)) +
    expand("rnd_{s}s_dis_{t}t_abcde", s=(200, 400), t=(50, 100, 150, 200)) +
    expand("rep_{s}s_dis_{t}t_abcde", s=(200, 400), t=(50, 100, 150, 200)) +
    expand("rep_{s}s_sim_{t}t_abcde", s=(200, 400), t=(50, 100, 150, 200))
)


rule all:
    input:
        expand(ipair("{b}").mstat, b=map(lambda p: str(p), iids)),
        expand(ipair("{b}").maxrep, b=map(lambda p: str(p), iids))

rule maxrep:
    input:
        i=ipair("{index_id}").s,
        t=ipair("{index_id}").rev_cst
    output:
        ipair("{index_id}").maxrep
    params:
        exe=dump_maxrep
    shell:
        "{params.exe} -s_path {input.i} -load_cst 1"

rule cst:
    input:
        ipair("{index_id}").s
    output:
        ipair("{index_id}").rev_cst, ipair("{index_id}").fwd_cst
    params:
        exe=dump_cst
    shell:
        "{params.exe} -s_path {input}"

rule slow:
    input:
        s=ipair("{inid}").s,
        t=ipair("{inid}").t
    output:
        ipair("{inid}").mstat
    params:
        exe=ms_slow
    shell:
        "{params.exe} -s_path {input.s} -t_path {input.t} > {output}"


rule gen_input:
    output:
        "{spolicy}_{slen}s_{tpolicy}_{tlen}t_abcde.s",
        "{spolicy}_{slen}s_{tpolicy}_{tlen}t_abcde.t",
    shell:
        ("python generate_input3.py --seed 1432 "
         "--rep_mut 10 "
         "--sim_mut 15 "
         "{wildcards.spolicy}_{wildcards.tpolicy} abcde {wildcards.slen} {wildcards.tlen}")
