import random
from pathlib import Path


def get_str(alp, size):
    return "".join(random.choice(alp) for i in range(size))

def get_compr(wildcards, input):
    return wildcards.compr

compr_list = "rrr, hybrid, rle, delta, succint, nibble".split(", ")

wildcard_constraints:
    compr="(" + ")|(".join(compr_list) + ")",
    suff="[st]"

rule all:
    input:
        expand("inp.t.ms.{c}", c=compr_list)
    
rule compress:
    input:
        ms="inp.t.ms"
    output:
        "inp.t.ms.{compr}"
    params:
        exec_path="../../../bin/compress_ms.x",
        compression=get_compr
    wrapper:
        "file:" + str(Path(".").absolute().parent)


rule ms:
    input:
        s="inp.s",
        t="inp.t",
    output:
        "inp.t.ms", "inp.t.ms.0", "inp.t.runs", "inp.t.runs.0"
    params:
        exec_path="../../../bin/matching_stats_parallel.x",
        lca_parents=1,
        rank_fail=1,
        double_rank=1,
    threads:
        8
    wrapper:
        "file:" + str(Path(Path(".").absolute().parent.parent, "ms"))



rule input:
    output:
        "inp.{suff}"
    run:
        with open(str(output), 'wt') as fd:
            fd.write(get_str('ab', 100))
