---
title: "range_report"
author: "odenas"
date: "August 14, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Max Range queries on vanilla compression 
```{r}
library(tidyverse)
rm(list=ls())

rel_diff_f <- function(a, b) (a - b) / pmax(a, b)
base_dir <- "./vanilla_compression_techniques/max"

algorithm_dot <- c("algorithm.select", "algorithm.blocks", 
                   "algorithm.trivial_case",  "algorithm.trivial_scan", 
                   "algorithm.rmq_query", "algorithm.rmq_scan")
range_dot <- c("range.bit", "range.block", "range.i_block", "range.int")
read_time_dataset <- function(input_id){
  time_dd <- (
    read_csv(sprintf("%s/%s.t.ms.csv", base_dir, input_id))
    %>% filter(method %in% c('algorithm', algorithm_dot, range_dot))
    %>% mutate(time_ms = time_ms / nqueries, dset=input_id)
  )
  time_dd
}


dd <- (
  rbind(
    read_time_dataset('HG03061-2')#, read_time_dataset("mm")
  )
  #%>% filter(compression=='none', algo == 't')
  #%>% select(-nqueries, -algo)
)
dd

size_dd <- (
  dd 
  %>% filter(method=='range.bit') 
  %>% group_by(block_size, range_size) %>% summarise(brsize=mean(time_ms))
  %>% ungroup() 
  %>% group_by(block_size) %>% mutate(d = rank(abs(block_size - range_size)))
  %>% ungroup() %>% filter(d == 1) %>% select(-d)
)
size_dd

time_dd <- (dd %>% filter(method %in% algorithm_dot, 
                          method != "algorithm.blocks", method != "algorithm.select", method != "algorithm.trivial_scan",
                          block_size != -128))
ggplot(time_dd, aes(range_size, time_ms, color=factor(method))) + 
  geom_line() + geom_point() + 
  geom_vline(data = size_dd, aes(xintercept=brsize, group=factor(block_size)), linetype="dashed", alpha=1) +
#  geom_text(data = size_dd %>% mutate(a=0.01 + runif(nrow(size_dd))/2), aes(brsize, a, label=brsize)) +
  facet_wrap(~block_size, scales = "free_x") +
  scale_x_log10() + scale_y_log10() + expand_limits(y=c(0, 1))

ggplot(time_dd, aes(range_size, time_ms, group=factor(block_size))) +
  geom_line(aes(color=factor(block_size))) + 
  geom_point(aes(color=factor(block_size))) + 
  geom_vline(data = size_dd, aes(xintercept=brsize, color=factor(block_size)), linetype="dashed", alpha=1) +
  geom_text(data = size_dd %>% mutate(a=0.01 + runif(nrow(size_dd))/2), aes(brsize, a, label=brsize)) +
  scale_x_log10() + scale_y_log10() + expand_limits(y=c(0, 1)) +
  facet_wrap(~dset)

time_dd <- (dd %>% filter(method=='algorithm'))





dd <- (
  rbind(read_time_dataset('HG03061-2'))#, read_time_dataset('mm'))
  %>% filter(block_size == 0)
  #%>% spread(method, time_ms)
  #%>% mutate(rel_diff = rel_diff_f(d, t), abs_diff = (d - t), speedup=t/d)
  #%>% select(dset, compression, block_size, method, d, t, rel_diff, abs_diff, speedup)
)

ggplot(dd, aes(range_size, time_ms, color=compression, linetype=algo, shape=algo)) +
  geom_line() + geom_point() +
  scale_x_log10() + scale_y_log10() + 
  facet_wrap(~dset)
```

none 1    < 4
none 1.73 < 4.75
none 2.14 < 6.29
rrr  6.50 > 4.38
rrr  8.16 > 5.47
rrr  15.9 > 12.5

```{r}
base_dir <- "./vanilla_compression_techniques"
read_sizes_dataset <- function(input_id){
  get_size <- function(e){
    file.info(sprintf('%s/%s.t.ms.%s', base_dir, input_id, e))$size
  }
  space_dd <- (
    tibble(compression = c('delta', 'nibble', 'none', 'rle', 'rrr', 'succint'))
    %>% mutate(size = sapply(compression, get_size))
  )
  
  space_dd <- rbind(space_dd, space_dd %>% filter(compression == 'none') %>% mutate(compression = 'word'))

  space_dd <- (
    space_dd %>% mutate(gr = 1)
    %>% inner_join(
      space_dd %>% filter(compression == "none") %>% transmute(gr = 1, nsize=size),
      by=c("gr"))
    %>% mutate(size_diff = rel_diff_f(size, nsize))
    %>% select(-gr)
  )
  space_dd  
}

space_dd <- rbind(read_sizes_dataset('HG03061-2') %>% mutate(dset='human_human'),
                  read_sizes_dataset('mm') %>% mutate(dset='chimp_human'))
space_dd
```

