---
title: "custom_input"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
rm(list=ls())
library(tidyverse)
source('utils.R')
```


```{r}
old_l <- sapply(seq(2, 40, 2), function(i) sprintf("rep_%d", i))
new_l <- sapply(c(1, seq(10, 200, 10)), function(i) sprintf("rep_%d", i))


time_data <- (rbind(
  read_many_csv(
    list.files('../input_stats_data/exploration/index_based_query/rev_labels/',
             pattern = '*lca.csv', full.names = TRUE)),
  read_many_csv(
    list.files('../input_stats_data/exploration/index_based_query/rev_labels/',
             pattern = '*pseq.csv', full.names = TRUE))
  ) %>% 
    filter(item %in% c('runs_bvector')) %>%
    separate(b_path, c('inp_type', 'lb', 'csv'), sep = "[.]") %>% 
    select(-len_s, -len_t, -item, -lb, -csv) %>% 
    mutate(alp = 'abcdef') %>% 
    mutate(inp_type = factor(inp_type, levels = new_l,
                             ordered = TRUE))
)


prange_plot(time_data %>% 
              spread(key = label, value = value) %>%  
              group_by(inp_type) %>% 
              mutate(rel_diff = (lca - mean(pseq)) / pmax(lca, mean(pseq)))) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size=8))


```


```{r}

istat_data <- (
  read_many_csv(
    list.files('../input_stats_data/exploration/index_based_query/rev_labels/',
               pattern='*.istat.csv', full.names = TRUE)) %>% 
    filter(measuring == 'pseq') %>% 
    mutate(key = as.numeric(key))
)
istat_data

ggplot(istat_data, aes(key, value, color=where)) + geom_point() + geom_line() + facet_wrap(~b_path) #+ xlim(1, 12)



```

# rank and fail


## firs trial
```{r}
new_l <- sapply(c(1, seq(10, 200, 10)), function(i) sprintf("rep_%d", i))

time_data <- (rbind(
  read_many_csv(
    list.files('../input_stats_data/exploration/index_based_query/rank_and_fail_test/',
             pattern = '*.l1_f0_r1_m0.csv', full.names = TRUE)) %>% 
    mutate(label = 'fail'),
  read_many_csv(
    list.files('../input_stats_data/exploration/index_based_query/rank_and_fail_test/',
             pattern = '*.l1_f1_r1_m0.csv', full.names = TRUE)) %>% 
    mutate(label = 'nofail')
  ) %>% 
    filter(item %in% c('runs_bvector')) %>%
    separate(b_path, c('inp_type', 'lb', 'csv'), sep = "[.]") %>% 
    select(-len_s, -len_t, -item, -lb, -csv) %>% 
    mutate(alp = 'abcdef') %>% 
    mutate(inp_type = factor(inp_type, levels = new_l,
                             ordered = TRUE))
)


prange_plot(time_data %>% 
              spread(key = label, value = value) %>%  
              group_by(inp_type) %>% 
              mutate(rel_diff = (fail - mean(nofail)) / pmax(fail, mean(nofail)))) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size=8))

```

## cooked example
```{r}
time_data <- (rbind(
  read_many_csv(
    list.files('../input_stats_data/exploration/cooked_stringXrank_and_fail/',
             pattern = '*.l1_f0_r1_m0.csv', full.names = TRUE)) %>% 
    mutate(label = 'fail'),
  read_many_csv(
    list.files('../input_stats_data/exploration/cooked_stringXrank_and_fail/',
             pattern = '*.l1_f1_r1_m0.csv', full.names = TRUE)) %>% 
    mutate(label = 'nofail')
  ) %>% 
    filter(item %in% c('runs_bvector')) %>% 
    separate(b_path, c('inp_type', 'period', 'l', 'f', 'r', 'm', 'suff')) %>% 
    select(-len_t, -len_s, -item, -l, -f, -r, -m, -suff) %>% 
    mutate(alp='abcd12345678') %>% 
    unite(inp_type, inp_type, period)
)

prange_plot(time_data %>% 
              spread(key = label, value = value) %>%  
              group_by(inp_type) %>% 
              mutate(rel_diff = (fail - mean(nofail)) / pmax(fail, mean(nofail)))) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size=8))

```

# periodical dollars
```{r}
new_l <- sapply(seq(20, 20, 20), function(i) sprintf("rnd_%d", i))

time_data <- (rbind(
  read_many_csv(
    list.files('../input_stats_data/exploration/a_simple_test_string/',
             pattern = '*lca.csv', full.names = TRUE)),
  read_many_csv(
    list.files('../input_stats_data/exploration/a_simple_test_string/',
             pattern = '*pseq.csv', full.names = TRUE))
  ) %>% 
    filter(item %in% c('runs_bvector')) %>%
    separate(b_path, c('inp_type', 'lb', 'csv'), sep = "[.]") %>% 
    select(-len_s, -len_t, -item, -lb, -csv) %>% 
    mutate(alp = 'abcdef') %>% 
    mutate(inp_type = factor(inp_type, levels = new_l,
                             ordered = TRUE))
)


prange_plot(time_data %>% 
              spread(key = label, value = value) %>%  
              group_by(inp_type) %>% 
              mutate(rel_diff = (lca - mean(pseq)) / pmax(lca, mean(pseq)))) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size=8))


```


```{r}

istat_data <- (
  read_many_csv(
    list.files('../input_stats_data/exploration/a_simple_test_string/',
               pattern='*.istat.csv', full.names = TRUE)) %>% 
    filter(measuring == 'pseq') %>% 
    mutate(key = as.numeric(key))
)
istat_data

ggplot(istat_data, aes(key, value, color=where)) + geom_point() + geom_line() + facet_wrap(~b_path) #+ xlim(1, 12)

```
