
RANK_TIMMING_SCRIPT   = /Users/denas/Library/Developer/Xcode/DerivedData/fast_ms-dtwaybjykudaehehgvtglnvhcjbp/Build/Products/Debug/single_vs_double_rank



rank_timing.csv : input_data/rnd_1Gs_5Mt.s
	$(RANK_TIMMING_SCRIPT) -load_cst 1 -s_path $< >$@

