---
title: "Genome matches"
author: "O. Denas"
date: "February 6, 2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Overlayed histograms of the $MS_{homo_sapiens,x}$ ($x$ is Mus_musculus and Danio Rerio).

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)

load_hist <- function(path){
  tt <- str_split(str_split(str_split(path, '/', simplify = T)[,3],
                            '[.]', simplify = T)[,1],
                  '_', simplify = T)
  block_size <- as.integer(str_sub(tt[,1], 2))
  sample_size <- as.integer(str_sub(tt[,2], 2))

  (read_delim(path, delim = ' ', col_names = c('ms', 'count'))
    %>% mutate(name = str_c(tt[,2], tt[,1], sep = "_"),
               block_size = block_size,
               sample_size = sample_size, prop = count / sum(count))
    %>% filter(!is.na(ms)))
}
dd <- do.call(rbind, lapply(list.files('pan_troglodytes/pt21_vs_hs21', pattern = "hist$", full.names = TRUE), load_hist))
ggplot(dd %>% filter(ms < 500), aes(ms, prop)) + geom_bar(stat='identity') + facet_wrap(~block_size, scales = 'free')

ff <- do.call(rbind, lapply(list.files('pan_troglodytes/pt21_vs_hs17', pattern = "hist$", full.names = TRUE), load_hist))
ggplot(ff %>% filter(ms < 500), aes(ms, prop)) + geom_bar(stat='identity') + facet_wrap(~block_size, scales = 'free')

ggplot(rbind(dd %>% filter(sample_size == 1, ms<500) %>% mutate(name = 'dd'),
             ff %>% filter(sample_size == 1, ms<100) %>% mutate(name = 'ff')),
       aes(ms, count)) + geom_bar(stat='identity') + facet_wrap(~name, scales = 'free')

rbind(dd %>% filter(sample_size == 1, ms < 500) %>% mutate(name = 'dd'),
      ff %>% filter(sample_size == 1, ms < 100) %>% mutate(name = 'ff'))
```

