---
title: "Untitled"
author: "O. Denas"
date: "October 15, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
library(knitr)
```

Let `t = abbaba` and `s=ab`.

We have

```{r}
ttt <- data.frame(i = 0:5,
                  t_i = c("a", "b", "b", "a", "b", "a"),
                  MS = c(2, 1, 1, 2, 1, 1),
                  ms = c("2 001", "0 1", "1 01", "2 001", "0 1", "1 01"),
                  runs = c(NaN, 1, 0, 0, 1, 0),
                  h = c("1", "", "3", "4", "", "6"))
kable(ttt)
```

and


```{r}

ttt <- data.frame(i = 0:2,
                  s_i = c("a", "b", "#"),
                  SA_s = c("2 #", "0 ab#", "1 b#"),
                  BWT_s = c("b", "#", "a"),
                  ss_i = c("b", "a", "#"),
                  SA_ss = c("2 #", "1 a#", "0 ba#"),
                  BWT_ss = c("a", "#", "b")
                  )
kable(ttt)
```

Algorithm I
```
[5] w = a(1, 1)  -->  ba(-, -)  p(w) = e(0, 2) --> b(2, 2)

[4] w = b(2, 2)  -->  ab(1, 1)  runs[4] = 1

[3] w = ab(1, 1) --> bab(-, -)  p(w) = e(0, 2) --> b(2, 2)

[2] w = b(2, 2)  -->  bb(-, -)  p(w) = e(0, 2) --> b(2, 2)

[1] w = b(2, 2)  -->  ab(1, 1)  runs[1] = 1
```

Algorithm II
```
[0] w = a(1, 1) --> ba(2, 2) --> bba(-, -)  h* = 2   p(ba) = e(0, 2)
                     e(0, 2) -->   b(2, 2)  k' = 2   h* - k - MS[0] + 1 = 2 --> 001

[2] w = b(2, 2) --> ab(-, -)                h* = 3   p(b) = e(0, 2)
        e(0, 2) -->  b(2, 2)                k' = 3   h* - k - MS[0] + 1 = 1 --> 01

[3] w = a(1, 1) --> ba(2, 2) --> aba(-, -)  h* = 5   p(ba) = e(0, 2)
        e(0, 2) -->  a(1, 1)                k' = 5   h* - k - MS[0] + 1 = 2 --> 001
```

## Scratch notes

```{r}
rm(list=ls())
set.seed(123)
N <- 50
going_up <- runif(N) > 0.5
jump <- rbinom(N, 20, 0.5)
xl <- lapply(1:N, function(i) if(going_up[i]) jump[i] else rep(-1, jump[i]))

ms <- cumsum(do.call(c, xl))
M <- length(ms)
runs <- c(0, ms[2:M] - ms[1:(M-1)])
plot(ms, type='b', col = 1 + (runs == -1), pch='.')
grid()

```